### ISSUE TITLE
Message `.toJSON()` method is unsafe

### ISSUE THREAD

**Issue by rovnyart** [deliveryhero/hfc-pubsub#96]
### Summary

I suppose it's not a big deal, but for me using `message.toJSON()` method was a bit confisung since it was unsafe. I think, if it exists and is represented in documentation, maybe we don't want it to crash the whole app=)

### Current Behavior

App crashes completely if I publish invalid json to PubSub topic and do `message.toJSON()` in my code. This doesn't go to `handleError`, just causes crash and process termination.

### Desired Behavior

I think this method should use try-catch internally and return undefined on parsing error. I can submit a pr with this change.

**Comment by rohit-gohri** [comment]
> I think, if it exists and is represented in documentation, maybe we don't want it to crash the whole app=)
> This doesn't go to handleError, just causes crash and process termination.

I will try to reproduce this behavior and get back to you. I think the current behavior was supposed to be to just nack the message and it should eventually end up in DLQ.

https://github.com/deliveryhero/hfc-pubsub/blob/f8e2f18a5f0ee39c993d647a06f8800dd80385b6/src/client/googlePubSub/index.ts#L124-L128

> I think this method should use try-catch internally and return undefined on parsing error

The library generally tries to throw on unexpected cases and let the user handle it, we don't want to make assumptions on how to handle invalid payloads. But it should definitely not crash the application if there is a `handleError` defined.

**Comment by rohit-gohri** [comment]
Hey @rovnyart, I tried to reproduce the issue and could not. The message just kept retrying (though without any error logs) and then ended up in the DLQ. Can you post a minimal reproduction?
